---
apiVersion: apps/v1
kind: Pod
metadata:
  name: nse-icmp-responder
  labels:
    app: nse-icmp-responder
spec:
  restartPolicy: Never
  containers:
    - name: nse-icmp-responder
      env:
        - name: NSE_CIDR_PREFIX
          value: 169.254.0.0/16
        - name: NSE_SERVICE_NAME
          value: autoscale-icmp-responder
        - name: NSE_LABELS
          value: app:nse-icmp-responder
        - name: NSE_IDLE_TIMEOUT
          value: 15s
