---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-supplier-k8s
spec:
  template:
    spec:
      containers:
        - name: nse-supplier
          env:
            - name: NSE_SERVICE_NAME
              value: autoscale-icmp-responder
            - name: NSE_LABELS
              value: app:supplier
            - name: NSE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
