---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsmgr-proxy-binding
subjects:
  - kind: ServiceAccount
    name: nsmgr-proxy-sa
    namespace: "default"
roleRef:
  kind: ClusterRole
  name: nsmgr-proxy-binding-role
  apiGroup: rbac.authorization.k8s.io
